[package]
name = "stellar-axelar-std-derive"
version = "1.1.0"
edition = { workspace = true }
description = "Proc macros for Axelar contracts."
license = { workspace = true }
publish = true

[lib]
proc-macro = true

[features]

[dependencies]
heck = "0.5"
itertools = "0.14"
prettyplease = { version = "0.2", default-features = false }
proc-macro2 = { workspace = true }
quote = { version = "1.0", default-features = false }
syn = { version = "2.0", default-features = false, features = ["derive", "extra-traits", "full", "parsing"] }

[dev-dependencies]
goldie = { workspace = true }

[lints]
workspace = true
